# fly.toml app configuration file generated for fastify-app-book-muddy-shape-2842 on 2024-01-09T23:49:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fastify-app-book-muddy-shape-2842"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[metrics]]
  port = 9001
  path = "/metrics"
